#!/bin/bash
cd /lonp
curl -sSL https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz -o new.tar.gz
tar -zxvf new.tar.gz
cd Zero*
python2 zeronet.py --ui_ip * --tor disable 
while :; do sleep 31104000 ; done
